package fxMitatuliostettua.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

import fxMitatuliostettua.*;
import mitatuliostettua.Kauppareissu;

/**
 * Test class made by ComTest
 * @version 2020.03.18 14:15:02 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KauppareissuTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi22 */
  @Test
  public void testRekisteroi22() {    // Kauppareissu: 22
    Kauppareissu eka = new Kauppareissu(); 
    assertEquals("From: Kauppareissu line: 24", 0, eka.getTunnus()); 
    eka.rekisteroi(); 
    eka.rekisteroi(); 
    Kauppareissu toka = new Kauppareissu(); 
    toka.rekisteroi(); 
    int tunnus1 = eka.getTunnus(); 
    int tunnus2 = toka.getTunnus(); 
    assertEquals("From: Kauppareissu line: 31", tunnus2-1, tunnus1); 
  } // Generated by ComTest END
}