package fxMitatuliostettua.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

import fxMitatuliostettua.*;
import mitatuliostettua.Kauppareissu;
import mitatuliostettua.Kauppareissut;

/**
 * Test class made by ComTest
 * @version 2020.03.18 22:24:38 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KauppareissutTest {



  // Generated by ComTest BEGIN
  /** testLisaa30 */
  @Test
  public void testLisaa30() {    // Kauppareissut: 30
    Kauppareissut kauppareissut = new Kauppareissut(); 
    Kauppareissu eka = new Kauppareissu(); 
    kauppareissut.lisaa(eka); 
    assertEquals("From: Kauppareissut line: 34", 1, kauppareissut.getLkm()); 
    Kauppareissu toka= new Kauppareissu(); 
    kauppareissut.lisaa(toka); 
    assertEquals("From: Kauppareissut line: 37", 2, kauppareissut.getLkm()); 
    assertEquals("From: Kauppareissut line: 38", eka, kauppareissut.annaViite(0)); 
    assertEquals("From: Kauppareissut line: 39", toka, kauppareissut.annaViite(1)); 
    Kauppareissu juu = new Kauppareissu(); 
    kauppareissut.lisaa(juu); 
    assertEquals("From: Kauppareissut line: 42", 3, kauppareissut.getLkm()); 
  } // Generated by ComTest END
}