package fxMitatuliostettua.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import fxMitatuliostettua.*;
import mitatuliostettua.Kauppareissu;
import mitatuliostettua.Mitatuliostettua;
// Generated by ComTest END
import mitatuliostettua.SailoException;

/**
 * Test class made by ComTest
 * @version 2020.03.18 23:45:51 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class MitatuliostettuaTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa27 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa27() throws SailoException {    // Mitatuliostettua: 27
    Mitatuliostettua mitatuliostettua = new Mitatuliostettua(); 
    Kauppareissu eka = new Kauppareissu(); 
    Kauppareissu toka = new Kauppareissu(); 
    assertEquals("From: Mitatuliostettua line: 32", 0, mitatuliostettua.getMaara()); 
    mitatuliostettua.lisaa(eka); 
    assertEquals("From: Mitatuliostettua line: 34", 1, mitatuliostettua.getMaara()); 
    mitatuliostettua.lisaa(toka); 
    assertEquals("From: Mitatuliostettua line: 36", 2, mitatuliostettua.getMaara()); 
    assertEquals("From: Mitatuliostettua line: 37", eka, mitatuliostettua.annaKauppareissu(0)); 
    assertEquals("From: Mitatuliostettua line: 38", toka, mitatuliostettua.annaKauppareissu(1)); 
    try {
    assertEquals("From: Mitatuliostettua line: 39", toka, mitatuliostettua.annaKauppareissu(2)); 
    fail("Mitatuliostettua: 39 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}