package mitatuliostettua.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import mitatuliostettua.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.25 20:30:37 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KauppareissutTest {



  // Generated by ComTest BEGIN
  /** testLisaa44 */
  @Test
  public void testLisaa44() {    // Kauppareissut: 44
    Kauppareissut kauppareissut = new Kauppareissut(); 
    Kauppareissu eka = new Kauppareissu(); 
    kauppareissut.lisaa(eka); 
    assertEquals("From: Kauppareissut line: 48", 1, kauppareissut.getLkm()); 
    Kauppareissu toka= new Kauppareissu(); 
    kauppareissut.lisaa(toka); 
    assertEquals("From: Kauppareissut line: 51", 2, kauppareissut.getLkm()); 
    assertEquals("From: Kauppareissut line: 52", eka, kauppareissut.annaViite(0)); 
    assertEquals("From: Kauppareissut line: 53", toka, kauppareissut.annaViite(1)); 
    Kauppareissu juu = new Kauppareissu(); 
    kauppareissut.lisaa(juu); 
    assertEquals("From: Kauppareissut line: 56", 3, kauppareissut.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLkm105 */
  @Test
  public void testGetLkm105() {    // Kauppareissut: 105
    Kauppareissut kauppareissut = new Kauppareissut(); 
    Kauppareissu eka = new Kauppareissu(); 
    kauppareissut.lisaa(eka); 
    assertEquals("From: Kauppareissut line: 109", 1, kauppareissut.getLkm()); 
    Kauppareissu toka= new Kauppareissu(); 
    kauppareissut.lisaa(toka); 
    assertEquals("From: Kauppareissut line: 112", 2, kauppareissut.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testMuokkaa124 */
  @Test
  public void testMuokkaa124() {    // Kauppareissut: 124
    Kauppareissut kauppareissut = new Kauppareissut(); 
    Kauppareissu kauppareissu = new Kauppareissu(); 
    kauppareissu.rekisteroi(); 
    kauppareissu.annaTiedot("20.03.2020"); 
    kauppareissut.lisaa(kauppareissu); 
    assertEquals("From: Kauppareissut line: 130", "20.03.2020", kauppareissu.getPvm()); 
    kauppareissut.muokkaa(kauppareissu, "11.03.2020"); 
    assertEquals("From: Kauppareissut line: 132", "11.03.2020", kauppareissu.getPvm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi317 
   * @throws SailoException when error
   */
  @Test
  public void testEtsi317() throws SailoException {    // Kauppareissut: 317
    Kauppareissut kauppareissut = new Kauppareissut(); 
    Kauppareissu kauppareissu1 = new Kauppareissu(); kauppareissu1.parse("1|20.03.2020|"); 
    Kauppareissu kauppareissu2 = new Kauppareissu(); kauppareissu2.parse("2|20.04.2020|"); 
    Kauppareissu kauppareissu3 = new Kauppareissu(); kauppareissu3.parse("3|20.05.2020|"); ; 
    kauppareissut.lisaa(kauppareissu1); kauppareissut.lisaa(kauppareissu2); kauppareissut.lisaa(kauppareissu3); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsiId362 
   * @throws SailoException when error
   */
  @Test
  public void testEtsiId362() throws SailoException {    // Kauppareissut: 362
    Kauppareissut kauppareissut = new Kauppareissut(); 
    Kauppareissu eka = new Kauppareissu(), toka = new Kauppareissu(), kolmas = new Kauppareissu(); 
    eka.rekisteroi(); toka.rekisteroi(); kolmas.rekisteroi(); 
    int id1 = eka.getTunnus(); 
    kauppareissut.lisaa(eka); kauppareissut.lisaa(toka); kauppareissut.lisaa(kolmas); 
    assertEquals("From: Kauppareissut line: 369", 1, kauppareissut.etsiId(id1+1)); 
    assertEquals("From: Kauppareissut line: 370", 2, kauppareissut.etsiId(id1+2)); 
  } // Generated by ComTest END
}