package mitatuliostettua.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import mitatuliostettua.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.24 15:15:46 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KauppareissutTest {



  // Generated by ComTest BEGIN
  /** testLisaa43 */
  @Test
  public void testLisaa43() {    // Kauppareissut: 43
    Kauppareissut kauppareissut = new Kauppareissut(); 
    Kauppareissu eka = new Kauppareissu(); 
    kauppareissut.lisaa(eka); 
    assertEquals("From: Kauppareissut line: 47", 1, kauppareissut.getLkm()); 
    Kauppareissu toka= new Kauppareissu(); 
    kauppareissut.lisaa(toka); 
    assertEquals("From: Kauppareissut line: 50", 2, kauppareissut.getLkm()); 
    assertEquals("From: Kauppareissut line: 51", eka, kauppareissut.annaViite(0)); 
    assertEquals("From: Kauppareissut line: 52", toka, kauppareissut.annaViite(1)); 
    Kauppareissu juu = new Kauppareissu(); 
    kauppareissut.lisaa(juu); 
    assertEquals("From: Kauppareissut line: 55", 3, kauppareissut.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi294 
   * @throws SailoException when error
   */
  @Test
  public void testEtsi294() throws SailoException {    // Kauppareissut: 294
    Kauppareissut kauppareissut = new Kauppareissut(); 
    Kauppareissu kauppareissu1 = new Kauppareissu(); kauppareissu1.parse("1|20.03.2020|"); 
    Kauppareissu kauppareissu2 = new Kauppareissu(); kauppareissu2.parse("2|20.04.2020|"); 
    Kauppareissu kauppareissu3 = new Kauppareissu(); kauppareissu3.parse("3|20.05.2020|"); ; 
    kauppareissut.lisaa(kauppareissu1); kauppareissut.lisaa(kauppareissu2); kauppareissut.lisaa(kauppareissu3); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsiId347 
   * @throws SailoException when error
   */
  @Test
  public void testEtsiId347() throws SailoException {    // Kauppareissut: 347
    Kauppareissut kauppareissut = new Kauppareissut(); 
    Kauppareissu eka = new Kauppareissu(), toka = new Kauppareissu(), kolmas = new Kauppareissu(); 
    eka.rekisteroi(); toka.rekisteroi(); kolmas.rekisteroi(); 
    int id1 = eka.getTunnus); 
    kauppareissut.lisaa(eka); kauppareissut.lisaa(toka); kauppareissut.lisaa(kolmas); 
    assertEquals("From: Kauppareissut line: 354", 1, kauppareissut.etsiId(id1+1)); 
    assertEquals("From: Kauppareissut line: 355", 2, kauppareissut.etsiId(id1+2)); 
  } // Generated by ComTest END
}