package mitatuliostettua.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import mitatuliostettua.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.19 12:35:20 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KauppareissuTest {



  // Generated by ComTest BEGIN
  /** testGetPvm22 */
  @Test
  public void testGetPvm22() {    // Kauppareissu: 22
    Kauppareissu eka = new Kauppareissu(); 
    eka.annaTiedot(); 
    assertEquals("From: Kauppareissu line: 25", "20.01.2018", eka.getPvm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi36 */
  @Test
  public void testRekisteroi36() {    // Kauppareissu: 36
    Kauppareissu eka = new Kauppareissu(); 
    assertEquals("From: Kauppareissu line: 38", 0, eka.getTunnus()); 
    eka.rekisteroi(); 
    eka.rekisteroi(); 
    Kauppareissu toka = new Kauppareissu(); 
    toka.rekisteroi(); 
    int tunnus1 = eka.getTunnus(); 
    int tunnus2 = toka.getTunnus(); 
    assertEquals("From: Kauppareissu line: 45", tunnus2-1, tunnus1); 
  } // Generated by ComTest END
}