package mitatuliostettua.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import mitatuliostettua.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.25 22:34:05 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KauppareissuTest {



  // Generated by ComTest BEGIN
  /** testGetPvm24 */
  @Test
  public void testGetPvm24() {    // Kauppareissu: 24
    Kauppareissu eka = new Kauppareissu(); 
    eka.annaTiedot("20.01.2018"); 
    assertEquals("From: Kauppareissu line: 27", "20.01.2018", eka.getPvm()); 
    Kauppareissu toka = new Kauppareissu(); 
    toka.annaTiedot("15.03.2020"); 
    assertEquals("From: Kauppareissu line: 30", "15.03.2020", toka.getPvm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi42 */
  @Test
  public void testRekisteroi42() {    // Kauppareissu: 42
    Kauppareissu eka = new Kauppareissu(); 
    assertEquals("From: Kauppareissu line: 44", 0, eka.getTunnus()); 
    eka.rekisteroi(); 
    eka.rekisteroi(); 
    Kauppareissu toka = new Kauppareissu(); 
    toka.rekisteroi(); 
    int tunnus1 = eka.getTunnus(); 
    int tunnus2 = toka.getTunnus(); 
    assertEquals("From: Kauppareissu line: 51", tunnus2-1, tunnus1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetTunnusNro121 */
  @Test
  public void testSetTunnusNro121() {    // Kauppareissu: 121
    Kauppareissu eka = new Kauppareissu(); 
    assertEquals("From: Kauppareissu line: 123", 0, eka.getTunnus()); 
    eka.setTunnusNro(2); 
    assertEquals("From: Kauppareissu line: 125", 2, eka.getTunnus()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString139 */
  @Test
  public void testToString139() {    // Kauppareissu: 139
    Kauppareissu kauppareissu = new Kauppareissu(); 
    kauppareissu.annaTiedot("20.03.2020"); 
    assertEquals("From: Kauppareissu line: 142", "0|20.03.2020", kauppareissu.toString()); 
    Kauppareissu rissu = new Kauppareissu(); 
    rissu.annaTiedot("06.05.2019"); 
    assertEquals("From: Kauppareissu line: 145", "0|06.05.2019", rissu.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse162 */
  @Test
  public void testParse162() {    // Kauppareissu: 162
    Kauppareissu kauppareissu = new Kauppareissu(); 
    kauppareissu.rekisteroi(); 
    kauppareissu.parse("1|06.05.2019"); 
    assertEquals("From: Kauppareissu line: 166", "06.05.2019", kauppareissu.getPvm()); 
    assertEquals("From: Kauppareissu line: 167", 1, kauppareissu.getTunnus()); 
    Kauppareissu rissu = new Kauppareissu(); 
    rissu.rekisteroi(); 
    rissu.parse("0|20.03.2020"); 
    assertEquals("From: Kauppareissu line: 171", "20.03.2020", rissu.getPvm()); 
    assertEquals("From: Kauppareissu line: 172", 0, rissu.getTunnus()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone195 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone195() throws CloneNotSupportedException {    // Kauppareissu: 195
    Kauppareissu kauppareissu = new Kauppareissu(); 
    kauppareissu.parse("0|10.02.2012"); 
    Kauppareissu kopio = kauppareissu.clone(); 
    Object olio = kauppareissu.clone(); 
    assertEquals("From: Kauppareissu line: 201", kauppareissu.toString(), kopio.toString()); 
    kauppareissu.parse("4|03.12.2020"); 
    assertEquals("From: Kauppareissu line: 203", false, kopio.toString().equals(kauppareissu.toString())); 
    assertEquals("From: Kauppareissu line: 204", true, olio instanceof Kauppareissu); 
  } // Generated by ComTest END
}