package mitatuliostettua.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import mitatuliostettua.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.24 14:59:14 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KauppareissuTest {



  // Generated by ComTest BEGIN
  /** testGetPvm24 */
  @Test
  public void testGetPvm24() {    // Kauppareissu: 24
    Kauppareissu eka = new Kauppareissu(); 
    eka.annaTiedot("20.01.2018"); 
    assertEquals("From: Kauppareissu line: 27", "20.01.2018", eka.getPvm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi39 */
  @Test
  public void testRekisteroi39() {    // Kauppareissu: 39
    Kauppareissu eka = new Kauppareissu(); 
    assertEquals("From: Kauppareissu line: 41", 0, eka.getTunnus()); 
    eka.rekisteroi(); 
    eka.rekisteroi(); 
    Kauppareissu toka = new Kauppareissu(); 
    toka.rekisteroi(); 
    int tunnus1 = eka.getTunnus(); 
    int tunnus2 = toka.getTunnus(); 
    assertEquals("From: Kauppareissu line: 48", tunnus2-1, tunnus1); 
  } // Generated by ComTest END
}