package mitatuliostettua.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import mitatuliostettua.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.30 16:07:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OstoTest {



  // Generated by ComTest BEGIN
  /** testAnna54 */
  @Test
  public void testAnna54() {    // Osto: 54
    Osto osto = new Osto(); 
    Tuoteryhma tuote = new Tuoteryhma(); 
    osto.annaTiedot(1, tuote, 2, 1); 
    assertEquals("From: Osto line: 58", "1", osto.anna(0)); 
    assertEquals("From: Osto line: 59", "2", osto.anna(2)); 
    assertEquals("From: Osto line: 60", "1", osto.anna(3)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetMaara92 */
  @Test
  public void testGetMaara92() {    // Osto: 92
    Kauppareissu kauppareissu = new Kauppareissu(); 
    kauppareissu.rekisteroi(); 
    kauppareissu.annaTiedot("20.02.2020"); 
    Osto eka = new Osto(); 
    eka.annaTiedot(1, "juu", 3, 2); 
    assertEquals("From: Osto line: 98", 3, eka.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi180 */
  @Test
  public void testRekisteroi180() {    // Osto: 180
    Osto eka = new Osto(); 
    Osto toka = new Osto(); 
    assertEquals("From: Osto line: 183", 0, eka.getTunnus()); 
    eka.rekisteroi(); 
    eka.rekisteroi(); 
    toka.rekisteroi(); 
    int tunnus1 = eka.getTunnus(); 
    int tunnus2 = toka.getTunnus(); 
    assertEquals("From: Osto line: 189", tunnus2-1, tunnus1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetTunnus203 */
  @Test
  public void testGetTunnus203() {    // Osto: 203
    Kauppareissu kauppareissu = new Kauppareissu(); 
    kauppareissu.rekisteroi(); 
    kauppareissu.annaTiedot("20.02.2020"); 
    Tuoteryhma tuote = new Tuoteryhma(); 
    tuote.rekisteroi(); 
    Osto eka = new Osto(); 
    eka.annaTiedot(1, tuote, 3, 2); 
    assertEquals("From: Osto line: 211", 0, eka.getTunnus()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString283 */
  @Test
  public void testToString283() {    // Osto: 283
    Tuoteryhma tuote = new Tuoteryhma(); 
    Tuoteryhmat tuoteryhmat = new Tuoteryhmat(); 
    tuoteryhmat.lisaa(tuote); 
    Osto osto = new Osto(); 
    osto.annaTiedot(1, tuote, 5, 3); 
    assertEquals("From: Osto line: 289", "0|0|1|null|5|3", osto.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse303 */
  @Test
  public void testParse303() {    // Osto: 303
    Tuoteryhmat tuoteryhmat = new Tuoteryhmat(); 
    Osto osto = new Osto(); 
    osto.rekisteroi(); 
    osto.parse("0|0|1|null|5|3", tuoteryhmat); 
    assertEquals("From: Osto line: 308", 5, osto.getMaara()); 
    assertEquals("From: Osto line: 309", 3, osto.getHinta()); 
    Osto rissu = new Osto(); 
    rissu.rekisteroi(); 
    rissu.parse("1|2|1|null|4|5", tuoteryhmat); 
    assertEquals("From: Osto line: 313", 5, rissu.getHinta()); 
    assertEquals("From: Osto line: 314", 4, rissu.getMaara());
    assertEquals("From: Osto line: 315", 1, rissu.getTunnus()); 
  } // Generated by ComTest END
}