package mitatuliostettua.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import mitatuliostettua.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.25 22:38:20 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OstoTest {



  // Generated by ComTest BEGIN
  /** testAnna58 */
  @Test
  public void testAnna58() {    // Osto: 58
    Osto osto = new Osto(); 
    Tuoteryhma tuote = new Tuoteryhma(); 
    osto.annaTiedot(1, tuote, 2, 1); 
    assertEquals("From: Osto line: 62", "1", osto.anna(0)); 
    assertEquals("From: Osto line: 63", "2", osto.anna(2)); 
    assertEquals("From: Osto line: 64", "1", osto.anna(3)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetMaara96 */
  @Test
  public void testGetMaara96() {    // Osto: 96
    Kauppareissu kauppareissu = new Kauppareissu(); 
    kauppareissu.rekisteroi(); 
    kauppareissu.annaTiedot("20.02.2020"); 
    Osto eka = new Osto(); 
    eka.annaTiedot(1, "juu", 3, 2); 
    assertEquals("From: Osto line: 102", 3, eka.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi184 */
  @Test
  public void testRekisteroi184() {    // Osto: 184
    Osto eka = new Osto(); 
    Osto toka = new Osto(); 
    assertEquals("From: Osto line: 187", 0, eka.getTunnus()); 
    eka.rekisteroi(); 
    eka.rekisteroi(); 
    toka.rekisteroi(); 
    int tunnus1 = eka.getTunnus(); 
    int tunnus2 = toka.getTunnus(); 
    assertEquals("From: Osto line: 193", tunnus2-1, tunnus1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetTunnus207 */
  @Test
  public void testGetTunnus207() {    // Osto: 207
    Kauppareissu kauppareissu = new Kauppareissu(); 
    kauppareissu.rekisteroi(); 
    kauppareissu.annaTiedot("20.02.2020"); 
    Tuoteryhma tuote = new Tuoteryhma(); 
    tuote.rekisteroi(); 
    Osto eka = new Osto(); 
    eka.annaTiedot(1, tuote, 3, 2); 
    assertEquals("From: Osto line: 215", 0, eka.getTunnus()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString287 */
  @Test
  public void testToString287() {    // Osto: 287
    Tuoteryhma tuote = new Tuoteryhma(); 
    Tuoteryhmat tuoteryhmat = new Tuoteryhmat(); 
    tuoteryhmat.lisaa(tuote); 
    Osto osto = new Osto(); 
    osto.annaTiedot(1, tuote, 5, 3); 
    assertEquals("From: Osto line: 293", "0|0|1|null|5|3", osto.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse307 */
  @Test
  public void testParse307() {    // Osto: 307
    Tuoteryhmat tuoteryhmat = new Tuoteryhmat(); 
    Osto osto = new Osto(); 
    osto.rekisteroi(); 
    osto.parse("0|0|1|null|5|3", tuoteryhmat); 
    assertEquals("From: Osto line: 312", 5, osto.getMaara()); 
    assertEquals("From: Osto line: 313", 3, osto.getHinta()); 
    Osto rissu = new Osto(); 
    rissu.rekisteroi(); 
    rissu.parse("1|2|1|null|4|5", tuoteryhmat); 
    assertEquals("From: Osto line: 317", 5, rissu.getHinta()); 
    assertEquals("From: Osto line: 318", 4, rissu.getMaara());
    assertEquals("From: Osto line: 319", 1, rissu.getTunnus()); 
  } // Generated by ComTest END
}