package mitatuliostettua.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import mitatuliostettua.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.03 22:54:23 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OstoTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi94 */
  @Test
  public void testRekisteroi94() {    // Osto: 94
    Osto eka = new Osto(); 
    assertEquals("From: Osto line: 96", 0, eka.getTunnus()); 
    eka.rekisteroi(); 
    eka.rekisteroi(); 
    Osto toka = new Osto(); 
    toka.rekisteroi(); 
    int tunnus1 = eka.getTunnus(); 
    int tunnus2 = toka.getTunnus(); 
    assertEquals("From: Osto line: 103", tunnus2-1, tunnus1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString187 */
  @Test
  public void testToString187() {    // Osto: 187
    Osto osto = new Osto(); 
    osto.parse("   1   |  2  |   alkoholi  | 6 | 10 "); 
    assertEquals("From: Osto line: 190", "1|2|alkoholi|6|10", osto.toString()); 
  } // Generated by ComTest END
}