package mitatuliostettua.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import mitatuliostettua.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.26 00:29:02 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OstotTest {



  // Generated by ComTest BEGIN
  /** testLisaa73 */
  @Test
  public void testLisaa73() {    // Ostot: 73
    Ostot ostot = new Ostot(); 
    Osto eka = new Osto(); 
    ostot.lisaa(eka); 
    assertEquals("From: Ostot line: 77", 1, ostot.getLkm()); 
    Osto toka = new Osto(); 
    ostot.lisaa(toka); 
    assertEquals("From: Ostot line: 80", 2, ostot.getLkm()); 
    Osto juu = new Osto(); 
    ostot.lisaa(juu); 
    assertEquals("From: Ostot line: 83", 3, ostot.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLkm202 */
  @Test
  public void testGetLkm202() {    // Ostot: 202
    Ostot ostot = new Ostot(); 
    Osto osto = new Osto(); 
    Osto esto = new Osto(); 
    osto.rekisteroi(); 
    esto.rekisteroi(); 
    ostot.lisaa(osto); 
    ostot.lisaa(esto); 
    assertEquals("From: Ostot line: 210", 2, ostot.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaOstot224 */
  @Test
  public void testAnnaOstot224() {    // Ostot: 224
    Ostot ostot = new Ostot(); 
    Osto eka = new Osto(2); ostot.lisaa(eka); 
    Osto toka = new Osto(1); ostot.lisaa(toka); 
    Osto kolmas = new Osto(2); ostot.lisaa(kolmas); 
    Osto neljas = new Osto(1); ostot.lisaa(neljas); 
    Osto viides = new Osto(2); ostot.lisaa(viides); 
    Osto kuudes = new Osto(5); ostot.lisaa(kuudes); 
    List<Osto> loytyneet; 
    loytyneet = ostot.annaOstot(3); 
    assertEquals("From: Ostot line: 237", 0, loytyneet.size()); 
    loytyneet = ostot.annaOstot(1); 
    assertEquals("From: Ostot line: 239", 2, loytyneet.size()); 
    assertEquals("From: Ostot line: 240", true, loytyneet.get(0) == toka); 
    assertEquals("From: Ostot line: 241", true, loytyneet.get(1) == neljas); 
    loytyneet = ostot.annaOstot(5); 
    assertEquals("From: Ostot line: 243", 1, loytyneet.size()); 
    assertEquals("From: Ostot line: 244", true, loytyneet.get(0) == kuudes); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLaskeHinta319 */
  @Test
  public void testLaskeHinta319() {    // Ostot: 319
    Kauppareissut kauppareissut = new Kauppareissut(); 
    Kauppareissu eka = new Kauppareissu(); 
    eka.rekisteroi(); 
    kauppareissut.lisaa(eka); 
    Osto osto = new Osto(); 
    Ostot ostot = new Ostot(); 
    osto.annaTiedot(eka.getTunnus(), "tuote", 3, 5); 
    Osto osto2 = new Osto(); 
    osto2.annaTiedot(eka.getTunnus(), "tuote2", 6, 7); 
    ostot.lisaa(osto); 
    ostot.lisaa(osto2); 
    assertEquals("From: Ostot line: 331", 12, ostot.laskeHinta(eka.getTunnus())); 
  } // Generated by ComTest END
}