package mitatuliostettua.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import mitatuliostettua.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.19 14:08:36 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TuoteryhmatTest {


  // Generated by ComTest BEGIN
  /** testLisaa32 */
  @Test
  public void testLisaa32() {    // Tuoteryhmat: 32
    Tuoteryhmat tuoteryhmat = new Tuoteryhmat(); 
    Tuoteryhma ruoka = new Tuoteryhma(); 
    tuoteryhmat.lisaa(ruoka); 
    assertEquals("From: Tuoteryhmat line: 36", 1, tuoteryhmat.getLkm()); 
    Tuoteryhma juoma = new Tuoteryhma(); 
    tuoteryhmat.lisaa(juoma); 
    assertEquals("From: Tuoteryhmat line: 39", 2, tuoteryhmat.getLkm()); 
    assertEquals("From: Tuoteryhmat line: 40", ruoka, tuoteryhmat.annaViite(0)); 
    assertEquals("From: Tuoteryhmat line: 41", juoma, tuoteryhmat.annaViite(1)); 
    Tuoteryhma joku = new Tuoteryhma(); 
    tuoteryhmat.lisaa(joku); 
    assertEquals("From: Tuoteryhmat line: 44", 3, tuoteryhmat.getLkm()); 
  } // Generated by ComTest END
}