package mitatuliostettua.test;
// Generated by ComTest BEGIN
import java.io.File;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import static org.junit.Assert.*;
import org.junit.*;
import mitatuliostettua.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.25 23:37:25 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TuoteryhmatTest {



  // Generated by ComTest BEGIN
  /** testLisaa48 */
  @Test
  public void testLisaa48() {    // Tuoteryhmat: 48
    Tuoteryhmat tuoteryhmat = new Tuoteryhmat(); 
    Tuoteryhma ruoka = new Tuoteryhma(); 
    tuoteryhmat.lisaa(ruoka); 
    assertEquals("From: Tuoteryhmat line: 52", 1, tuoteryhmat.getLkm()); 
    Tuoteryhma juoma = new Tuoteryhma(); 
    tuoteryhmat.lisaa(juoma); 
    assertEquals("From: Tuoteryhmat line: 55", 2, tuoteryhmat.getLkm()); 
    assertEquals("From: Tuoteryhmat line: 56", ruoka, tuoteryhmat.annaViite(0)); 
    assertEquals("From: Tuoteryhmat line: 57", juoma, tuoteryhmat.annaViite(1)); 
    Tuoteryhma joku = new Tuoteryhma(); 
    tuoteryhmat.lisaa(joku); 
    assertEquals("From: Tuoteryhmat line: 60", 3, tuoteryhmat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta114 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta114() throws SailoException {    // Tuoteryhmat: 114
    Tuoteryhmat tuoteryhmat = new Tuoteryhmat(); 
    Tuoteryhma eka = new Tuoteryhma(), toka = new Tuoteryhma(); 
    eka.annaTiedot("moi"); 
    toka.annaTiedot("hei"); 
    String hakemisto = "testiii"; 
    String tiedNimi = hakemisto+"/tuoteryhmt"; 
    File ftied = new File(tiedNimi+".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    tuoteryhmat.lueTiedostosta(tiedNimi); 
    tuoteryhmat.lisaa(eka); 
    tuoteryhmat.lisaa(toka); 
    tuoteryhmat.tallennaTuoteryhma(); 
    tuoteryhmat = new Tuoteryhmat();  // Poistetaan vanhat luomalla uusi
    tuoteryhmat.lueTiedostosta(tiedNimi);  // johon ladataan tiedot tiedostosta.
    Iterator<Tuoteryhma> i = tuoteryhmat.iterator(); 
    assertEquals("From: Tuoteryhmat line: 135", true, i.hasNext()); 
    tuoteryhmat.lisaa(toka); 
    tuoteryhmat.tallennaTuoteryhma(); 
    assertEquals("From: Tuoteryhmat line: 138", false, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Tuoteryhmat line: 140", false, fbak.delete()); 
    assertEquals("From: Tuoteryhmat line: 141", true, dir.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEtsi311 */
  @Test
  public void testEtsi311() {    // Tuoteryhmat: 311
    Tuoteryhmat tuoteryhmat = new Tuoteryhmat(); 
    Tuoteryhma tuoteryhma = new Tuoteryhma(); 
    Tuoteryhma tuote = new Tuoteryhma(); 
    tuoteryhmat.lisaa(tuoteryhma);
    tuoteryhmat.lisaa(tuote);
    Collection<Tuoteryhma> loytyneet = new ArrayList<Tuoteryhma>(); 
    loytyneet.add(tuoteryhma); 
    loytyneet.add(tuote); 
    assertEquals("From: Tuoteryhmat line: 320", loytyneet, tuoteryhmat.etsi("", 0)); 
  } // Generated by ComTest END
}