package mitatuliostettua.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import mitatuliostettua.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.24 15:15:02 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TuoteryhmatTest {



  // Generated by ComTest BEGIN
  /** testLisaa48 */
  @Test
  public void testLisaa48() {    // Tuoteryhmat: 48
    Tuoteryhmat tuoteryhmat = new Tuoteryhmat(); 
    Tuoteryhma ruoka = new Tuoteryhma(); 
    tuoteryhmat.lisaa(ruoka); 
    assertEquals("From: Tuoteryhmat line: 52", 1, tuoteryhmat.getLkm()); 
    Tuoteryhma juoma = new Tuoteryhma(); 
    tuoteryhmat.lisaa(juoma); 
    assertEquals("From: Tuoteryhmat line: 55", 2, tuoteryhmat.getLkm()); 
    assertEquals("From: Tuoteryhmat line: 56", ruoka, tuoteryhmat.annaViite(0)); 
    assertEquals("From: Tuoteryhmat line: 57", juoma, tuoteryhmat.annaViite(1)); 
    Tuoteryhma joku = new Tuoteryhma(); 
    tuoteryhmat.lisaa(joku); 
    assertEquals("From: Tuoteryhmat line: 60", 3, tuoteryhmat.getLkm()); 
  } // Generated by ComTest END
}