package mitatuliostettua.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import mitatuliostettua.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.19 13:46:07 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TuoteryhmaTest {



  // Generated by ComTest BEGIN
  /** testGetTuoteryhma18 */
  @Test
  public void testGetTuoteryhma18() {    // Tuoteryhma: 18
    Tuoteryhma ruoka  = new Tuoteryhma(); 
    ruoka.annaTiedot(); 
    assertEquals("From: Tuoteryhma line: 21", "ruoka", ruoka.getTuoteryhma()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi32 */
  @Test
  public void testRekisteroi32() {    // Tuoteryhma: 32
    Tuoteryhma ruoka= new Tuoteryhma(); 
    assertEquals("From: Tuoteryhma line: 34", 0, ruoka.getTunnus()); 
    ruoka.rekisteroi(); 
    Tuoteryhma juoma = new Tuoteryhma(); 
    juoma.rekisteroi(); 
    int tunnus1 = ruoka.getTunnus(); 
    int tunnus2 = juoma.getTunnus(); 
    assertEquals("From: Tuoteryhma line: 40", tunnus2-1, tunnus1); 
  } // Generated by ComTest END
}